<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Final Test D</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>6326aa31-55b9-4b24-9fcb-3dd1706cbeed</testSuiteGuid>
   <testCaseLink>
      <guid>3c84daaa-a673-4f7c-b82c-84be207de0d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BOX/Test Login with valid credentials</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>102c8b13-aceb-421c-9545-4b9b4487c694</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13174997-850d-459f-9737-6ff54910f0ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d79c634-f87c-4fc8-a28b-09efed7e2ce7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BOX/Test Login with valid credentials - Fails</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2787a98-9cd5-4966-aa41-fa42b4eb5aff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6970081d-7202-4822-8632-d954497e1cba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e995207e-4a7e-459c-b3e1-c5ed02e88b85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BOX/Test Login with invalid credentials</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>676cbe14-b46c-481e-abcf-dbd64aaa08eb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
