<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>S1_BoxFeatures0519A</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e4c99ad6-dc2a-4065-9126-e1936b07263d</testSuiteGuid>
   <testCaseLink>
      <guid>42ea7e31-0f8e-47df-bb10-97ab38fc9e0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BOX/RunFeatures/LoginFeature</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1896b928-c880-43c7-847a-f9c34f868680</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c30cc305-8386-4468-95d8-0251e47a9914</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BOX/RunFeatures/LogOutFeature</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20f18a99-fa32-4d32-bb57-64121fcdf2ee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c2ed809-b500-48c6-a07b-8e3870039ff1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BOX/RunFeatures/DownloadFeature</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e865f70-b97d-4e46-a762-6c007dd897e0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
