<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_New</name>
   <tag></tag>
   <elementGuidId>f7cec35e-02d0-46cb-a19e-d4cd6e05ef55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@class='btn-content'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menubutton13</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aaab3f80-1079-4b27-a889-c2ca646c42d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn create-dropdown-menu-toggle-button</value>
      <webElementGuid>132806be-4a10-4cfd-99d8-c034c3c6ba3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>363df132-06ec-46e8-9750-fc74c969280c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>8113b248-8530-40e5-a31f-056efdc26ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resin-target</name>
      <type>Main</type>
      <value>unifiednewmenubutton</value>
      <webElementGuid>08ea6bbe-263c-4eb5-90c2-cfeebe5ff633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>new-item-menu-button</value>
      <webElementGuid>7089ceaa-c323-40cd-bde1-d1112307b208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menubutton13</value>
      <webElementGuid>36279395-b997-44ae-83e6-90c12a0b8501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>362ca51f-2d50-4625-b56b-729cfa67f169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6227f3ec-1471-4ada-ab1e-f08bb83ac65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>875e4442-ef92-49df-87b9-4ed1011eba3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menubutton13&quot;)</value>
      <webElementGuid>0515874c-637a-45d0-80c0-e71f9a8eff3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='menubutton13']</value>
      <webElementGuid>24ecc274-8747-485a-90c0-2cd3a35967d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[5]/span/div/div[2]/main/div/div/div/div/div[2]/div/div/span[2]/span/div/button</value>
      <webElementGuid>8c14c675-0b71-4918-b7b5-817a707ceaa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Files'])[3]/following::button[2]</value>
      <webElementGuid>d3f96fc0-f264-493a-be3e-c1de7c6f7861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Files'])[2]/following::button[3]</value>
      <webElementGuid>3d75be33-e9ea-44d4-bec3-fbc7026ff327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Files'])[1]/preceding::button[1]</value>
      <webElementGuid>088d21da-fe0a-48ef-af85-c6a84928a38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/div/button</value>
      <webElementGuid>cb9509cc-d741-4a0b-afe1-dd0801d9654f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'menubutton13' and (text() = 'New' or . = 'New')]</value>
      <webElementGuid>74a03ea1-2ae9-4a21-b9c5-94b68ed980ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
