<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FileGet Started with Box.pdfAll FilesModified May 16, 2023 by Bob Dylan1.8 MBShow More OptionsCopy Shared LinkShareSelect</name>
   <tag></tag>
   <elementGuidId>9816f626-0cc9-47fb-ab03-45b4a10da012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contextmenutarget251</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contextmenutarget251']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f2ec538-d843-4553-a6ac-59f0fd8b7cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2c5af497-5815-454b-b9f7-c804bd4e3179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-list-view-item</value>
      <webElementGuid>85641b91-bb9a-4d61-b64d-616a2cf1248a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ca41228d-daf0-429a-ae2d-518317a3dd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>7cd8d98c-19a6-4c58-8e6d-b7a173b32fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>68876fe7-1db6-401e-a2da-668670dd00db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contextmenutarget251</value>
      <webElementGuid>0089b740-7099-418b-9172-558445c8b221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FileGet Started with Box.pdfAll FilesModified May 16, 2023 by Bob Dylan∙1.8 MBShow More OptionsCopy Shared LinkShareSelect</value>
      <webElementGuid>c6e1eb0d-052d-43bc-b942-86241acb1531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contextmenutarget251&quot;)</value>
      <webElementGuid>c2ad4f8f-75b9-4022-95a5-f9b65f01ec31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='contextmenutarget251']</value>
      <webElementGuid>17389550-6a0c-476d-9714-766442cc219f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[5]/span/div/div[2]/main/div/div/div[3]/div/div[2]/div/div[2]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>4783d2f7-9a09-44e6-b005-81491d41fdd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relevance'])[2]/following::div[10]</value>
      <webElementGuid>056049a8-eb9c-45d4-9ded-d0317a4df6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[2]/following::div[10]</value>
      <webElementGuid>417ee952-0aa0-4903-8911-47841b969b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>d17f4db8-0025-40cc-b413-d5df81d84f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'contextmenutarget251' and (text() = 'FileGet Started with Box.pdfAll FilesModified May 16, 2023 by Bob Dylan∙1.8 MBShow More OptionsCopy Shared LinkShareSelect' or . = 'FileGet Started with Box.pdfAll FilesModified May 16, 2023 by Bob Dylan∙1.8 MBShow More OptionsCopy Shared LinkShareSelect')]</value>
      <webElementGuid>6fb2362e-7a12-4a44-9eff-f7237ee0effc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
