<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_File Upload</name>
   <tag></tag>
   <elementGuidId>bc198013-cf7b-40d1-a98c-4b22b7b65c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;menu12&quot;)/div[1]/div[@class=&quot;scroll-container&quot;]/div[@class=&quot;scroll-wrap-container style--cover&quot;]/span[@class=&quot;bdl-targeted-click-through&quot;]/li[@class=&quot;menu-item UploadMenuItem&quot;][count(. | //li[@class = 'menu-item UploadMenuItem' and @role = 'menuitem' and (text() = 'File Upload' or . = 'File Upload')]) = count(//li[@class = 'menu-item UploadMenuItem' and @role = 'menuitem' and (text() = 'File Upload' or . = 'File Upload')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='bdl-targeted-click-through']//li[@role='menuitem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.UploadMenuItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>88236dd5-bb3b-4b38-8fbb-142052cd92ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item UploadMenuItem</value>
      <webElementGuid>32a2aa49-004b-4b49-bfac-25e1959d69d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>49f48139-9d51-456d-86f1-618e6f148521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ac7eb6d6-284a-4bd6-b724-5920985d7829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>File Upload</value>
      <webElementGuid>68c1ea22-6f43-4ff2-a679-994717f5f62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu12&quot;)/div[1]/div[@class=&quot;scroll-container&quot;]/div[@class=&quot;scroll-wrap-container style--cover&quot;]/span[@class=&quot;bdl-targeted-click-through&quot;]/li[@class=&quot;menu-item UploadMenuItem&quot;]</value>
      <webElementGuid>9c69bfe5-2438-40a8-93b4-019fdb3627ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu12']/div/div[2]/div/span/li</value>
      <webElementGuid>4a687c8d-03fd-4fec-afde-0da80cd405b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New item in'])[1]/following::li[1]</value>
      <webElementGuid>8b3b9255-1337-4779-86a0-254ca0819720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Files and Folders'])[1]/following::li[1]</value>
      <webElementGuid>5adec4a2-3399-4a73-a583-c9653bf259d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folder Upload'])[1]/preceding::li[1]</value>
      <webElementGuid>5440f182-3f8f-41eb-abb5-bcb7d944f01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/li</value>
      <webElementGuid>cabb74f9-7d57-437c-b673-b3f8e8249d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'File Upload' or . = 'File Upload')]</value>
      <webElementGuid>fb10ac84-78cb-4b65-9566-6007eda2d3ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
