<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BD</name>
   <tag></tag>
   <elementGuidId>50fdd286-97ea-4036-9da2-4fa2fe473055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menubutton51']/div/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>00dcada3-6a69-4ae4-9a13-a46dd21c826c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar-initials </value>
      <webElementGuid>e272122b-7953-41a7-a1aa-e89dfcbdcb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bg-idx</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>30e490ad-c52d-4f38-8059-ad5d3f553ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BD</value>
      <webElementGuid>615cdeb8-5d46-4b8a-be25-3077aedaf42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menubutton51&quot;)/div[@class=&quot;ProfileButton-avatar&quot;]/div[@class=&quot;badgeable-container avatar&quot;]/span[1]/span[@class=&quot;avatar-initials&quot;]</value>
      <webElementGuid>f9c79774-0bf4-42f6-bce8-a95bba62993d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='menubutton51']/div/div/span/span</value>
      <webElementGuid>7e8d4423-8f51-4108-b08d-fcd746448d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upgrade Plan'])[1]/following::span[2]</value>
      <webElementGuid>164b0a1e-7465-4a0a-a725-4733f4d3f055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag items here for quick access'])[1]/following::span[6]</value>
      <webElementGuid>842b835c-86f3-499d-96b0-c57e4651e8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Files'])[2]/preceding::span[1]</value>
      <webElementGuid>022040e0-0940-4702-832a-aeae3789ea00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Files'])[3]/preceding::span[1]</value>
      <webElementGuid>976c11e9-7600-4593-9633-eca17c85276c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BD']/parent::*</value>
      <webElementGuid>bb4c30f2-1701-420c-9d87-5bc501fb51f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span</value>
      <webElementGuid>056ac9ce-ea7d-499a-a419-57ac4daeec78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'BD' or . = 'BD')]</value>
      <webElementGuid>5399d1e1-c932-4037-b6d1-a809fc8c6969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='menubutton56']/div/div/span/span</value>
      <webElementGuid>50cb55ee-4918-4dbc-a626-a5bdb13e596f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::span[15]</value>
      <webElementGuid>64f39516-67d2-49fc-a265-44e71c503e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Files'])[1]/preceding::span[1]</value>
      <webElementGuid>abacd72c-41b5-4da8-ae28-87cff112a0ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
