<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_BD</name>
   <tag></tag>
   <elementGuidId>50fdd286-97ea-4036-9da2-4fa2fe473055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menubutton56']/div/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>76bfefb1-cb49-45bc-b30e-bb967cdcc7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar-initials </value>
      <webElementGuid>12a6fc04-5f3e-494f-b301-9c3a29d9c049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bg-idx</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>daa2813e-01ff-44d8-8eb8-d44b8374371d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BD</value>
      <webElementGuid>0943a73a-df21-45f9-9c90-667d954d0057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menubutton56&quot;)/div[@class=&quot;ProfileButton-avatar&quot;]/div[@class=&quot;badgeable-container avatar&quot;]/span[1]/span[@class=&quot;avatar-initials&quot;]</value>
      <webElementGuid>3d4a0625-e852-44fb-b0b8-ece2c1f946a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='menubutton56']/div/div/span/span</value>
      <webElementGuid>50cb55ee-4918-4dbc-a626-a5bdb13e596f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upgrade Plan'])[1]/following::span[2]</value>
      <webElementGuid>42d945a3-104f-41df-b676-8d29ab10ab8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag items here for quick access'])[1]/following::span[6]</value>
      <webElementGuid>fd5e2f9e-c872-4f68-922d-9eb36a6091be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Files'])[2]/preceding::span[1]</value>
      <webElementGuid>88590389-1546-417d-bb93-90ede5bd5b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Files'])[3]/preceding::span[1]</value>
      <webElementGuid>9e391d16-0432-4e29-b041-e18ad9b33d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BD']/parent::*</value>
      <webElementGuid>b2c82932-8ab0-46dd-b26e-9104269d4985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span</value>
      <webElementGuid>061fd003-039b-4c6b-9bda-40fad1883773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'BD' or . = 'BD')]</value>
      <webElementGuid>080163cf-a509-4075-86c0-efbb6e459514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='menubutton51']/div/div/span/span</value>
      <webElementGuid>5cdeae40-338c-4d21-b9b9-2f7505fb89a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::span[15]</value>
      <webElementGuid>64f39516-67d2-49fc-a265-44e71c503e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Files'])[1]/preceding::span[1]</value>
      <webElementGuid>abacd72c-41b5-4da8-ae28-87cff112a0ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
