<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Share_preview-close-btn</name>
   <tag></tag>
   <elementGuidId>4834da45-91b4-4724-b0ed-ae10541b1769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[5]/span/div/span/div/header/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.preview-close-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3486f632-d2ab-4b66-8577-0d0439c14927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close Preview</value>
      <webElementGuid>8bd8ac70-4b32-47a2-a6a7-94db4c245628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>preview-close-btn</value>
      <webElementGuid>5f96c590-1696-4edf-9d63-6969d9b389af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resin-target</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>6b980126-321e-4918-92a3-ba8f1f87efe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>preview-close-button</value>
      <webElementGuid>9806816c-0f5f-413b-a51f-db672c3299f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/folder/0</value>
      <webElementGuid>0c0da8ab-649c-4668-82fc-00711c351b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;in-app-messenger-provider&quot;]/span[@class=&quot;hotkey-layer&quot;]/div[@class=&quot;end-user has-header has-left-nav has-enhanced-styles has-no-page-content-level-left-padding has-no-page-content-level-right-padding has-sidebar&quot;]/span[@class=&quot;hotkey-layer preview-overlay is-preview-sidebar-visible&quot;]/div[@class=&quot;preview-container&quot;]/header[@class=&quot;preview-header&quot;]/a[@class=&quot;preview-close-btn&quot;]</value>
      <webElementGuid>aa66dd9d-93f9-442f-9151-248b72606b02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[5]/span/div/span/div/header/a</value>
      <webElementGuid>755c6df8-08b0-4100-8705-053332f7c570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[2]/following::a[1]</value>
      <webElementGuid>c31582fe-741a-4166-9633-7a7f3f8d90fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::a[1]</value>
      <webElementGuid>fa25a28c-d2c5-4682-bc5c-b5a288aeb60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zeke Kelly'])[1]/preceding::a[1]</value>
      <webElementGuid>8b60db0b-0517-4516-a0ee-7ca4c189fbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner'])[1]/preceding::a[1]</value>
      <webElementGuid>6bea2051-322a-4c0a-baa4-e216a277c0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/folder/0')])[6]</value>
      <webElementGuid>31936a1c-1b76-470d-ae45-20b1e9d67763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/a</value>
      <webElementGuid>b3f077aa-3eae-4677-8a45-f622a1959682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/folder/0']</value>
      <webElementGuid>75545418-340c-42c8-a7a5-08cf5a2a1490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
