<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Download</name>
   <tag></tag>
   <elementGuidId>b467ee4f-59f4-4dd0-987d-e4a75b24564e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[13]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.preview-responsive-btn.tooltip-target.tooltip-element-attached-top.tooltip-element-attached-center.tooltip-target-attached-bottom.tooltip-target-attached-center.tooltip-enabled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75bc735a-e69f-4bf8-ba0a-c8637d6248b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn preview-responsive-btn tooltip-target tooltip-element-attached-top tooltip-element-attached-center tooltip-target-attached-bottom tooltip-target-attached-center tooltip-enabled</value>
      <webElementGuid>5036baf3-6021-4987-8c90-3f4a7fc6a719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>60852a7a-c3ae-4105-a6bc-25a4d959314a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resin-item_id</name>
      <type>Main</type>
      <value>1215224276018</value>
      <webElementGuid>57e70417-052c-406a-9ad6-3a173e74facd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resin-target</name>
      <type>Main</type>
      <value>download</value>
      <webElementGuid>3deed783-e5d6-4f7d-9cc8-6cb83ed7379f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>download-button</value>
      <webElementGuid>ccf4d319-89d3-4e8c-9118-9c9d5961dae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c38b48af-637f-4000-a321-9072b1bb7500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip156</value>
      <webElementGuid>7e500dab-04af-430c-a837-de2f3a1d427c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>bca68ccc-903b-4771-8908-a7c56eca813c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;in-app-messenger-provider&quot;]/span[@class=&quot;hotkey-layer&quot;]/div[@class=&quot;end-user has-header has-left-nav has-enhanced-styles has-no-page-content-level-left-padding has-no-page-content-level-right-padding has-sidebar&quot;]/span[@class=&quot;hotkey-layer preview-overlay is-preview-sidebar-visible&quot;]/div[@class=&quot;preview-container&quot;]/header[@class=&quot;preview-header&quot;]/div[@class=&quot;preview-header-right&quot;]/button[@class=&quot;btn preview-responsive-btn tooltip-target tooltip-element-attached-top tooltip-element-attached-center tooltip-target-attached-bottom tooltip-target-attached-center tooltip-enabled&quot;]</value>
      <webElementGuid>fc1c5b24-9126-42ce-8173-aaa5115cd67f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[13]</value>
      <webElementGuid>34d3e602-f440-4647-9194-c64023ef8357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[5]/span/div/span/div/header/div[2]/button[2]</value>
      <webElementGuid>f8db2e7d-0df8-48e5-8c71-9820429f73ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/following::button[1]</value>
      <webElementGuid>31ca7c3c-d167-48bd-ab16-f9976423c362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updated Yesterday by Bob Dylan'])[1]/following::button[3]</value>
      <webElementGuid>3a07c02b-146e-4556-9817-3ae383ecc8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[2]/preceding::button[2]</value>
      <webElementGuid>dfedcda1-df92-47f6-8fbf-b9f9cf45cfab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>8e7099fa-bf8a-4d9a-be97-d3a251df3638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>084ca788-36dc-41f7-84a3-60ea25550921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
